//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockifyWeb.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/StockifyWS/ExistenciasWS")]
        public string StockifyWeb_localhost_ExistenciasWS {
            get {
                return ((string)(this["StockifyWeb_localhost_ExistenciasWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/StockifyWS/ProductoWS")]
        public string StockifyWeb_localhost_ProductoWS {
            get {
                return ((string)(this["StockifyWeb_localhost_ProductoWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/StockifyWS/MovimientoWS")]
        public string StockifyWeb_localhost_MovimientoWS {
            get {
                return ((string)(this["StockifyWeb_localhost_MovimientoWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/StockifyWS/OrdenSalidaWS")]
        public string StockifyWeb_localhost_OrdenSalidaWS {
            get {
                return ((string)(this["StockifyWeb_localhost_OrdenSalidaWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/StockifyWS/OrdenCompraWS")]
        public string StockifyWeb_localhost_OrdenCompraWS {
            get {
                return ((string)(this["StockifyWeb_localhost_OrdenCompraWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/StockifyWS/CuentaUsuarioWS")]
        public string StockifyWeb_localhost_CuentaUsuarioWS {
            get {
                return ((string)(this["StockifyWeb_localhost_CuentaUsuarioWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/StockifyWS/OrdenVentaWS")]
        public string StockifyWeb_localhost_OrdenVentaWS {
            get {
                return ((string)(this["StockifyWeb_localhost_OrdenVentaWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/StockifyWS/CategoriaWS")]
        public string StockifyWeb_localhost_CategoriaWS {
            get {
                return ((string)(this["StockifyWeb_localhost_CategoriaWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/StockifyWS/UsuarioWS")]
        public string StockifyWeb_localhost_UsuarioWS {
            get {
                return ((string)(this["StockifyWeb_localhost_UsuarioWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/StockifyWS/OrdenIngresoWS")]
        public string StockifyWeb_localhost_OrdenIngresoWS {
            get {
                return ((string)(this["StockifyWeb_localhost_OrdenIngresoWS"]));
            }
        }
    }
}
